#!/usr/bin/env python3.4

import argparse
import json
import rpc
import sys

parser = argparse.ArgumentParser(description='Postfix config exporter. Generates virtual email addresses for postfix')

parser.add_argument('--url', default='http://localhost:8080/rpc', help='url of rpc server to connect to. default: %(default)s')
parser.add_argument('--insecure', action='store_true', help='dont verify SSL certificates. (use with self-signed certificates)')
parser.add_argument('--destination', default="tracer", help='postfix destination. default: tracer')
parser.add_argument('--api_key', required=True, default=None, help='api key')

args = parser.parse_args()

try:
	#initialise the rpc client class
	rpc_client=rpc.RpcClient(args.url, insecure=args.insecure)

	result=rpc_client.request("core.Users.get_all_global", api_key=args.api_key)

	domains=set()
	for address in result["data"]:
		(bla,domain)=address.split("@")
		domains.add(domain)
		print(address+" "+args.destination)

	#is possible with postfix to define domains in the same virtual-file.
	for domain in domains:
		print(domain+" "+'""')

except Exception as e:
	print("Error: "+str(e), file=sys.stderr)
	sys.exit(1)



