#!/bin/bash
# For a proper rpc-client try ./client/cli


# Add initial admin mongo CLI:
# db.models.core.Users.insert({ "name":"admin", password:"yourpassss", "groups":["admin"], "active": true})



if [ "$1" == "" ]; then
    echo "For example:"
    echo  "./call core Users login '{\"name\":\"admin\", \"password\":\"admin\"}'"
    echo 
    echo "It remembers cookies, hence sessions"
    exit 1
fi

curl -b ./.cookies -c ./.cookies --data-binary "{ \"debug\":true, \"help\":true, \"module\":\"$1\",\"class\":\"$2\", \"method\":\"$3\", \"params\":$4}" -H "Content-Type: application/json"  http://localhost:8080/rpc
echo


