services:

  memcached:
   image: memcached
  kmur: 
   build: .
   volumes:
     - .:/app
     - data:/app/files/
   ports:
     - 20080:80
  db:
    image: mongo
    volumes:
      - db:/data


volumes:
  data:
  db:









