#!/bin/bash

DB=tracer_$1
 
echo 'db.models.core.Users.insert( { "active": "1", "name": "admin", "password": "changeme", "roles" : [ "admin" ], "group_ids": []  } )' | mongo $DB


mkdir files/$DB/
touch files/$DB/index.html

mkdir static/files/$DB/
touch static/files/$DB/index.html

chmod -R 770 static/files/$DB files/$DB
chgrp -R www-data static/files/$DB files/$DB 

